services:
  app:
    build:
      context: .
      dockerfile: ./apps/mail/Dockerfile
    env_file:
      - .env
    depends_on:
      db:
        condition: service_started
      migrate:
        condition: service_completed_successfully
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    ports:
      - "5173:5173"
    env_file:
      - .env
    volumes:
      - api_logs:/var/logs/
    depends_on:
      db:
        condition: service_started
      migrate:
        condition: service_completed_successfully
  db:
    image: postgres:9.6
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
  migrate:
    build:
      context: .
      dockerfile: ./packages/db/Dockerfile
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db_data:
  api_logs:
